# Generated by Django 4.2.1 on 2023-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_receipt_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='house_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
